### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by sanyavertolet** [teamvolik/teamvolik#12]
We need to think about deployment. To my mind we should have a script for that. It might also be nice to add Makefile in order to run linters locally.

**Comment by dgreflex** [comment]
What is the need to use linters locally if all code will be checked by linters at the development stage?

**Comment by dgreflex** [comment]
This does not make any sense, since if the code was checked by the linter at the development stage, then locally the linter will not detect errors anyway.

**Comment by sanyavertolet** [comment]
This is what @FrBrGeorge wants us to do.

**Comment by dgreflex** [comment]
Ok
